---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodeapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapp
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  # Add hpa spec as per requirement
  # Refer: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#creating-the-autoscaler-declaratively
